[package]
name = "hermod"
version = "0.1.0"
authors = ["TheGalidor"]
edition = "2018"

[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", features = ["json", "templates", "handlebars_templates"] }
serde = { version = "1", features = ["derive"] }
base64 = "0.11"
rand = "0.7"